### PR TITLE
Development

### PR DESCRIPTION
**Pull request by jgross11**
You break it you buy it - 50% working 50% of the time working system

### CODE REVIEW

**Review by Zachary-Ronayne — DISMISSED** [review]
Yes

**Comment by Acanzano6613** [comment]
Yeah

**Comment by Acanzano6613** [comment]
ye

**Review by Acanzano6613 — APPROVED** [review]
ye

**Review by Zachary-Ronayne — DISMISSED** [review]
Yes 2 electric boogaloo

**Pull request closed without merging**
